#!/bin/bash

curl -ik -XPOST -d '{"mac_address_range": {"cidr": "AA:BB:CC"}}' -H "Content-Type: application/json" -H "X-Auth-Project-Id: nova" -H "X-Auth-Token: admin:nova" http://127.0.0.1:9696/v2.0/mac_address_ranges
echo;
