#!/bin/bash

curl -ik -XPOST -d '{"ip_address": {"network_id": "70fa5f0a-8dab-464f-bbd8-65228505aab6", "device_id": "foobar", "version": "10"}}' -H "Content-Type: application/json" -H "X-Auth-Project-Id: nova" -H "X-Auth-Token: admin:nova" http://127.0.0.1:9696/v2.0/ip_addresses
echo;
